name: TimeSeries JS Client Build and Publish

on:
  release:
  workflow_dispatch:

jobs:
  build-and-test:
    uses: ./.github/workflows/lib/build-and-test.yml

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn ci
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
